### ISSUE TITLE
segfaults occasionally while model is training

### ISSUE THREAD

**Issue by rohan-varma** [ucla-labx/distbelief#12]
traces:
`[1]    98051 segmentation fault  /opt/homebrew/bin/python3.5 first_node.py`

`libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
[1]    98060 abort      /opt/homebrew/bin/python3.5 second_node.py`

**Comment by jcaip** [comment]
resolved by removing `model.share_memory()` which i think was causing some of the problems
